declare const API_KEY: string;
declare module "@atlaskit/toggle";
declare module "@atlaskit/drawer";
declare module "@atlaskit/tooltip";
declare module "@atlaskit/css-reset";
declare module "@atlaskit/blanket";
declare module "@atlaskit/theme";
declare module "react-intl-tel-input";
declare module "react-intl-tel-input/dist/main.css";
declare module "@opuscapita/react-dates";
declare module "react-multi-email";
declare type GlobalFetch = WindowOrWorkerGlobalScope;
